package:
  name: neuroseries
  version: 0.3.2

source:
  git_rev: 0.3.2
  git_url: https://github.com/MemDynLab/neuroseries.git

requirements:
  host:
    - python=3.7
    - setuptools

  run:
    - python=3.7
    - numpy
    - pandas>=0.23
    - git
    - ipython
    - psutil
    - parameterized

test:
  imports:
    - neuroseries
  source_files:
    - neuroseries/tests/test_neuroseries.py


about:
  home: https://github.com/MemDynLab/neuroseries
  license: GPL3
  license_file: LICENSE.txt